name: test

on: [push]

jobs:
  test:
    #где запускаем
    runs-on: ubuntu-latest
    #что делаем
    steps:
      #выкачиваем репу
      - uses: actions/checkout@v3
      #настраиваем java
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
      #даем права на запуск
      - run: chmod +x gradlew
      #добавляем селеноид
      - uses: Xotabu4/selenoid-github-action@v2

      #запуск тестов
      - run: ./gradlew clean test -Dselenide.remote=http://localhost:4444/wd/hub
